# Generated by Django 4.1.3 on 2022-12-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("new", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpredictdatamodel",
            name="age",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="userpredictdatamodel",
            name="avg_glucose_level",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="userpredictdatamodel",
            name="bmi",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="userpredictdatamodel",
            name="gender",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="userpredictdatamodel",
            name="heart_disease",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="userpredictdatamodel",
            name="hypertension",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="userpredictdatamodel",
            name="smoking_status",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="userpredictdatamodel",
            name="stroke",
            field=models.CharField(max_length=100),
        ),
    ]
